using UnityEngine;
using System.Collections;

[System.Serializable]
public partial class c_GuiCommonStyleController : MonoBehaviour
{
    /*****************************************************************************************
* The styles of all GUI layers
* 
* @author N-Game Studios 
* Research & Development
* 
*****************************************************************************************/
    public GUISkin guiSkin;
    public GUIStyle emptystyle;
    // === common elements ===
    public GUIStyle cf_blackscreenelement;
    public GUIStyle gui_common_menu_background;
    public GUIStyle gui_common_button_map;
    public GUIStyle gui_common_button_map_hover;
    public GUIStyle gui_common_button_ufo;
    public GUIStyle gui_common_button_ufo_hover;
    public GUIStyle gui_common_button_inventory;
    public GUIStyle gui_common_button_inventory_hover;
    public GUIStyle gui_common_button_exit;
    public GUIStyle gui_common_button_exit_hover;
    public GUIStyle gui_common_ufo_blur_background;
    public GUIStyle gui_common_button_disabled;
    public GUIStyle gui_common_button_normal;
    public GUIStyle gui_common_button_red;
    public GUIStyle gui_common_popup;
    public GUIStyle gui_common_button_close;
    public GUIStyle gui_common_button_close_dark;
    public GUIStyle gui_common_minigame_window;
    public GUIStyle gui_common_button_world;
    // === loading screen ===
    public GUIStyle gui_loading_background;
    public GUIStyle gui_loading_background_01;
    public GUIStyle gui_loading_background_02;
    public GUIStyle gui_loading_background_03;
    public GUIStyle gui_loading_background_04;
    public GUIStyle gui_loading_background_05;
    public GUIStyle gui_loading_logo;
    public GUIStyle gui_loading_loader_back;
    public GUIStyle gui_loading_loader;
    // === WorldMap screen ===
    public GUIStyle gui_worldmap_background;
    public GUIStyle gui_worldmap_button_map;
    public GUIStyle gui_worldmap_button_ship;
    public GUIStyle gui_worldmap_button_character;
    public GUIStyle gui_worldmap_button_shop;
    public GUIStyle gui_worldmap_button_exit;
    public GUIStyle gui_worldmap_button_entry;
    // === test screens ===
    public GUIStyle gui_test_background;
    public GUIStyle gui_exitwindow_background;
    public GUIStyle gui_test_button;
    public GUIStyle gui_test_island;
    public GUIStyle gui_test_sea;
    // === inventory screen ===
    public GUIStyle gui_inventory_background;
    public GUIStyle gui_inventory_character;
    public GUIStyle gui_inventory_drink;
    public GUIStyle gui_inventory_food;
    public GUIStyle gui_inventory_premium_icon;
    public GUIStyle gui_inventory_hover_slot;
    public GUIStyle gui_inventory_armor_icon;
    public GUIStyle gui_inventory_backpack_icon;
    public GUIStyle gui_inventory_boots_icon;
    public GUIStyle gui_inventory_feature_icon;
    public GUIStyle gui_inventory_gloves_icon;
    public GUIStyle gui_inventory_weapons_icon;
    public GUIStyle gui_inventory_button_make_out;
    public GUIStyle gui_inventory_button_make_out_d;
    public GUIStyle gui_inventory_button_use;
    public GUIStyle gui_inventory_button_use_d;
    public GUIStyle gui_inventory_button_trashbin;
    public GUIStyle gui_inventory_button_trashbin_d;
    public GUIStyle gui_inventory_experience;
    public GUIStyle gui_inventory_experience_background;
    public GUIStyle gui_inventory_experience_right_part;
    public GUIStyle gui_inventory_athletics;
    public GUIStyle gui_inventory_literature_languages;
    public GUIStyle gui_inventory_maths;
    public GUIStyle gui_inventory_natural_science;
    public Texture gui_inventory_hero_render;// = new AudioClip(); = new Texture();
    public GUIStyle gui_inventory_cells;
    public GUIStyle gui_inventory_cells_no_backpack;
    public GUIStyle gui_inventory_symbol;
    public GUIStyle gui_inventory_heart;
    public GUIStyle gui_inventory_healthbar_full;
    public GUIStyle gui_inventory_healthbar_empty;
    public GUIStyle gui_inventory_armor;
    public GUIStyle gui_inventory_damage;
    public GUIStyle gui_inventory_status_fullhealth;
    // === Icons ===
    public GUIStyle thing_icons_shoes_test;
    // === Dialogue Screen ===
    public GUIStyle gui_dialogue_background;
    public GUIStyle gui_dialogue_hog2_background;
    public GUIStyle gui_dialogue_hog3_background;
    public GUIStyle gui_dialogue_block_add;
    public GUIStyle gui_dialogue_block_background;
    public GUIStyle gui_dialogue_button_close;
    public GUIStyle gui_dialogue_button_left;
    public GUIStyle gui_dialogue_button_right;
    public GUIStyle gui_dialogue_button_yes;
    public GUIStyle gui_dialogue_button_no;
    public GUIStyle gui_dialogue_hero_avatar;
    public GUIStyle gui_dialogue_masha_avatar;
    public GUIStyle gui_dialogue_name_background;
    public GUIStyle gui_dialogue_girl_avatar;
    public Texture gui_dialogue_sectoid_render;// = new AudioClip();= new Texture();
    public Texture gui_dialogue_zoe_render;// = new Texture();
    public Texture gui_dialogue_kot_render;// = new Texture();
    // === Mushrooms Minigame Screen ===
    public GUIStyle gui_minigame_background;
    public GUIStyle gui_minigame_slot;
    public GUIStyle gui_minigame_mushroom_01;
    public GUIStyle gui_minigame_mushroom_02;
    public GUIStyle gui_minigame_mushroom_03;
    public GUIStyle gui_minigame_mushroom_04;
    public GUIStyle gui_minigame_mushroom_01_icon;
    public GUIStyle gui_minigame_mushroom_02_icon;
    public GUIStyle gui_minigame_mushroom_03_icon;
    public GUIStyle gui_minigame_mushroom_04_icon;
    public GUIStyle gui_minigame_mushroom_01_popup;
    public GUIStyle gui_minigame_popup_background;
    public GUIStyle gui_minigame_popup_ban;
    public GUIStyle gui_minigame_popup_bigle_frowning;
    public GUIStyle gui_minigame_popup_bigle_normal;
    public GUIStyle gui_minigame_popup_smartie;
    public GUIStyle gui_minigame_popup_wrong;
    // === Mushrooms Minigame Screen ===
    public GUIStyle gui_vegame_background;
    public GUIStyle gui_vegame_slots;
    public GUIStyle gui_vegame_button_long;
    public GUIStyle gui_vegame_stone;
    public GUIStyle gui_vegame_button_long_d;
    public GUIStyle gui_vegame_stone_d;
    public GUIStyle gui_vegame_hint;
    public GUIStyle gui_vegame_popup;
    public GUIStyle gui_vegame_sectoid;
    public GUIStyle gui_vegame_sectoid_sad;
    public GUIStyle gui_minigame_vegetable_01;
    public GUIStyle gui_minigame_vegetable_02;
    public GUIStyle gui_minigame_vegetable_03;
    public GUIStyle gui_minigame_vegetable_04;
    public GUIStyle gui_minigame_vegetable_05;
    public GUIStyle gui_minigame_vegetable_06;
    public GUIStyle gui_minigame_vegetable_07;
    public GUIStyle gui_minigame_vegetable_08;
    public GUIStyle gui_minigame_vegetable_09;
    public GUIStyle gui_minigame_vegetable_10;
    public GUIStyle gui_minigame_vegetable_11;
    public GUIStyle gui_minigame_vegetable_01_icon;
    public GUIStyle gui_minigame_vegetable_02_icon;
    public GUIStyle gui_minigame_vegetable_03_icon;
    public GUIStyle gui_minigame_vegetable_04_icon;
    public GUIStyle gui_minigame_vegetable_05_icon;
    public GUIStyle gui_minigame_vegetable_06_icon;
    public GUIStyle gui_minigame_vegetable_07_icon;
    public GUIStyle gui_minigame_vegetable_08_icon;
    public GUIStyle gui_minigame_vegetable_09_icon;
    public GUIStyle gui_minigame_vegetable_10_icon;
    public GUIStyle gui_minigame_vegetable_11_icon;
    // === Fishing Minigame Screen ===
    public GUIStyle gui_fishing_background;
    public GUIStyle gui_fishing_frame;
    public GUIStyle gui_fishing_counter;
    public GUIStyle gui_fishing_worm;
    public GUIStyle gui_fishing_hook;
    public GUIStyle gui_fishing_rod_1;
    public GUIStyle gui_fishing_rod_1_select;
    public GUIStyle gui_fishing_rod_2;
    public GUIStyle gui_fishing_rod_2_select;
    public GUIStyle gui_fishing_rod_3;
    public GUIStyle gui_fishing_rod_3_select;
    public GUIStyle gui_fish01_start;
    public GUIStyle gui_fish01_idle;
    public GUIStyle gui_fish01_end;
    public GUIStyle gui_fish02_start;
    public GUIStyle gui_fish02_idle;
    public GUIStyle gui_fish02_end;
    public GUIStyle gui_fish03_start;
    public GUIStyle gui_fish03_idle;
    public GUIStyle gui_fish03_end;
    public GUIStyle gui_fishing_popup_success;
    public GUIStyle gui_fishing_popup_failure;
    public GUIStyle gui_fishing_popup_seatrout;
    public GUIStyle gui_fishing_popup_seabass;
    public GUIStyle gui_fishing_popup_mullet;
    // === Battle Screen ===
    public GUIStyle gui_battlescreen_heart;
    public GUIStyle gui_battlescreen_healtbar_background;
    public GUIStyle gui_battlescreen_healtbar_health;
    public GUIStyle gui_battlescreen_herolevel;
    public GUIStyle gui_battlescreen_abilities_panel;
    public GUIStyle gui_battlescreen_shad;
    public GUIStyle gui_battlescreen_ability01;
    public GUIStyle gui_battlescreen_ability01_select;
    public GUIStyle gui_battlescreen_ability02;
    public GUIStyle gui_battlescreen_ability03;
    public GUIStyle gui_battlescreen_ability04;
    public GUIStyle gui_battlescreen_ability05;
    public GUIStyle gui_battlescreen_ability06;
    public GUIStyle gui_battlescreen_livebattle;
    public GUIStyle gui_battlescreen_mobhealth_background;
    public GUIStyle gui_battlescreen_mobhealth;
    // === Craft Screen ===
    public GUIStyle gui_craftscreen_panel_background;
    public GUIStyle gui_craftscreen_icon;
    public GUIStyle gui_craftscreen_selection;
    public GUIStyle gui_craftscreen_tab_craft_active;
    public GUIStyle gui_craftscreen_tab_craft_inactive;
    public GUIStyle gui_craftscreen_tab_makeout_active;
    public GUIStyle gui_craftscreen_tab_makeout_inactive;
    // === Library Screen ===
    public GUIStyle gui_library_background;
    public GUIStyle gui_library_book_slots;
    public GUIStyle gui_library_book_info;
    public GUIStyle gui_library_book_unread;
    public GUIStyle gui_library_book_read;
    public GUIStyle gui_library_section;
    public GUIStyle gui_library_booktitle_food;
    public GUIStyle gui_library_booktitle_mushrooms;
    public GUIStyle gui_library_booktitle_spacesuits;
    public GUIStyle gui_library_booktitle_spiders;
    public GUIStyle gui_library_booktitle_vegetables;
    public GUIStyle gui_library_tab_health_n;
    public GUIStyle gui_library_tab_health_s;
    public GUIStyle gui_library_tab_biology_n;
    public GUIStyle gui_library_tab_biology_s;
    public GUIStyle gui_library_tab_geo_n;
    public GUIStyle gui_library_tab_geo_s;
    public GUIStyle gui_library_tab_tech_n;
    public GUIStyle gui_library_tab_tech_s;
    public GUIStyle gui_library_tab_history_n;
    public GUIStyle gui_library_tab_history_s;
    public GUIStyle gui_library_symbol;
    public GUIStyle gui_library_icon_flash_food_on;
    public GUIStyle gui_library_icon_flash_food_off;
    public GUIStyle gui_library_icon_flash_mushrooms_on;
    public GUIStyle gui_library_icon_flash_mushrooms_off;
    public GUIStyle gui_library_icon_flash_skaf_on;
    public GUIStyle gui_library_icon_flash_skaf_off;
    public GUIStyle gui_library_icon_flash_spiders_on;
    public GUIStyle gui_library_icon_flash_spiders_off;
    public GUIStyle gui_library_icon_flash_vegetables_on;
    public GUIStyle gui_library_icon_flash_vegetables_off;
    // === UFO Screen ===
    public GUIStyle gui_ufoscreen_background;
    public GUIStyle gui_ufoscreen_ufo;
    public GUIStyle gui_ufoscreen_footnote1;
    public GUIStyle gui_ufoscreen_footnote2;
    public GUIStyle gui_ufoscreen_footnote3;
    public GUIStyle gui_ufoscreen_footnote4;
    public GUIStyle gui_ufoscreen_footnote5;
    public GUIStyle gui_ufoscreen_footnote6;
    public GUIStyle gui_ufoscreen_ufo_symbol;
    // === Kitchen Screen ===
    public GUIStyle gui_kitchen_background;
    public GUIStyle gui_kitchen_symbol;
    public GUIStyle gui_kitchen_recipe_background;
    public GUIStyle gui_kitchen_highlight_frame;
    public GUIStyle gui_kitchen_ingridients_background;
    public GUIStyle gui_workroom_symbol;
    // === Storage Screen ===
    public GUIStyle gui_storage_background;
    public GUIStyle gui_storage_background_no_backpack;
    public GUIStyle gui_storage_symbol;
    public GUIStyle gui_storage_faraway_background;
    public GUIStyle gui_storage_faraway_background_no_backpack;
    // === TUTORIAL ===
    public GUIStyle gui_tutorial_ufo_dialogue_background;
    public GUIStyle gui_tutorial_isle_dialogue_background;
    public GUIStyle gui_tutorial_sectoid_avatar;
    public GUIStyle gui_tutorial_cot_avatar;
    public GUIStyle gui_tutorial_kitchen_select;
    public GUIStyle gui_tutorial_fuckerarrow_up;
    public GUIStyle gui_tutorial_fuckerarrow_down;
    public GUIStyle gui_tutorial_fuckerarrow_left;
    public GUIStyle gui_tutorial_fuckerarrow_right;
    public GUIStyle gui_tutorial_icon_chicken_soup;
    public GUIStyle gui_tutorial_icon_mushroom_soup;
    public GUIStyle gui_tutorial_icon_potatoes_mushrooms;
    public GUIStyle gui_tutorial_icon_fish_soup;
    public GUIStyle gui_tutorial_icon_smoothies;
    public GUIStyle gui_tutorial_icon_cabbage_soup;
    public GUIStyle gui_tutorial_icon_food_chicken;
    public GUIStyle gui_tutorial_icon_food_potatoes;
    public GUIStyle gui_tutorial_icon_food_carrot;
    public GUIStyle gui_tutorial_icon_food_onion;
    public GUIStyle gui_tutorial_icon_feature;
    public GUIStyle gui_tutorial_icon_paralizator;
    public GUIStyle gui_tutorial_icon_blaster;
    public GUIStyle gui_tutorial_flash_anim;
    public GUIStyle gui_tutorial_fuckerarrow_sheet;
    // === Villa Screen ===
    public GUIStyle gui_villa_background;
    public GUIStyle gui_villa_symbol;
    public GUIStyle gui_villa_button_hog;
    // === HOG Screen ===
    public GUIStyle gui_hogscreen_panel;
    public GUIStyle gui_hogscreen_button_help;
    public GUIStyle gui_hogscreen_found;
    public GUIStyle gui_hogscreen_help_fx;
    public GUIStyle gui_hogscreen_goldenframe;
    public GUIStyle gui_hogscreen_goldenframe_anim;
    // === HOG1 ===
    public GUIStyle gui_hog1_background;
    public GUIStyle gui_hog1_item_swimming_mask;
    public GUIStyle gui_hog1_item_blurf_board;
    public GUIStyle gui_hog1_item_flippers;
    public GUIStyle gui_hog1_item_mikroskop;
    public GUIStyle gui_hog1_item_doll;
    public GUIStyle gui_hog1_item_bear;
    public GUIStyle gui_hog1_item_notebook;
    public GUIStyle gui_hog1_item_book;
    public GUIStyle gui_hog1_item_globus;
    public GUIStyle gui_hog1_item_virt;
    public GUIStyle gui_hog1_icon_swimming_mask;
    public GUIStyle gui_hog1_icon_blurf_board;
    public GUIStyle gui_hog1_icon_mikroskop;
    public GUIStyle gui_hog1_icon_doll;
    public GUIStyle gui_hog1_icon_bear;
    public GUIStyle gui_hog1_icon_notebook;
    public GUIStyle gui_hog1_icon_book;
    public GUIStyle gui_hog1_icon_virt;
    public GUIStyle gui_hog1_light;
    public GUIStyle gui_hog1_virt_sheet;
    // === HOG2 ===
    public GUIStyle gui_hog2_background;
    public GUIStyle gui_hog2_item_dinosaur;
    public GUIStyle gui_hog2_item_ammonit;
    public GUIStyle gui_hog2_item_locomotive;
    public GUIStyle gui_hog2_item_statue_egypt;
    public GUIStyle gui_hog2_item_ship;
    public GUIStyle gui_hog2_item_legionnaire;
    public GUIStyle gui_hog2_icon_dinosaur;
    public GUIStyle gui_hog2_icon_ammonit;
    public GUIStyle gui_hog2_icon_locomotive;
    public GUIStyle gui_hog2_icon_statue_egypt;
    public GUIStyle gui_hog2_icon_ship;
    public GUIStyle gui_hog2_icon_legionnaire;
    public GUIStyle gui_hog2_light;
    public GUIStyle gui_hog2_ammonit_sheet;
    // === Museum Screen ===
    public GUIStyle gui_museum_symbol;
    public GUIStyle gui_museum_unknown;
    public GUIStyle gui_museum_icon_virt;
    public GUIStyle gui_museum_icon_ammonit;
    public GUIStyle gui_exhibit_title_ammonit;
    public GUIStyle gui_exhibit_title_cd;
    // === No Way PopUp ===
    public GUIStyle gui_noway_image;
    // === Icons ===
    //Предметы (крафт)
    public GUIStyle gui_RecipeItemIcon01;
    public GUIStyle gui_RecipeItemIcon02;
    public GUIStyle gui_RecipeItemIcon03;
    public GUIStyle gui_RecipeItemIcon04;
    public GUIStyle gui_RecipeItemIcon05;
    //Компоненты для крафта предметов
    public GUIStyle gui_icons_loot_metal;
    public GUIStyle gui_icons_loot_plastic;
    public GUIStyle gui_icons_loot_cobweb;
    public GUIStyle gui_icons_loot_deadspider;
    public GUIStyle gui_icons_loot_eballon;
    public GUIStyle gui_icons_loot_cactus;
    //Еда (крафт)
    public GUIStyle gui_icons_food_chicken_soup;
    public GUIStyle gui_icons_food_cabbage_soup;
    public GUIStyle gui_icons_food_mushroom_soup;
    public GUIStyle gui_icons_food_mushroom_potatoes;
    public GUIStyle gui_icons_food_fish_soup;
    public GUIStyle gui_icons_food_pancake;
    public GUIStyle gui_icons_food_smoothies;
    public GUIStyle gui_icons_food_milkshape;
    //Компоненты для крафта еды
    public GUIStyle gui_icons_food_banana;
    public GUIStyle gui_icons_food_berries;
    public GUIStyle gui_icons_food_cabbage;
    public GUIStyle gui_icons_food_carrot;
    public GUIStyle gui_icons_food_chicken;
    public GUIStyle gui_icons_food_egg;
    public GUIStyle gui_icons_food_fish;
    public GUIStyle gui_icons_food_flour;
    public GUIStyle gui_icons_food_milk;
    public GUIStyle gui_icons_food_mushrooms;
    public GUIStyle gui_icons_food_onion;
    public GUIStyle gui_icons_food_orange;
    public GUIStyle gui_icons_food_potatoes;
    public GUIStyle gui_icons_food_sourcream;
    public GUIStyle gui_icons_food_spice;
    public GUIStyle gui_icons_food_beans;
    public GUIStyle gui_icons_food_chickpea;
    public GUIStyle gui_icons_food_corn;
    public GUIStyle gui_icons_food_kidney_beans;
    public GUIStyle gui_icons_food_lentils;
    public GUIStyle gui_icons_food_peanut;
    public GUIStyle gui_icons_food_peas;
    //Инвентарь
    public GUIStyle gui_icons_crystal_premium;
    public GUIStyle gui_icons_thing_r3_backpack;
    public GUIStyle gui_icons_thing_r3_gun;
    public GUIStyle gui_icons_thing_r3_hand;
    public GUIStyle gui_icons_thing_r4_gun;
    public GUIStyle gui_icons_thing_r4_leg;
    public GUIStyle gui_icons_thing_r4_hand;
    public GUIStyle gui_icons_thing_r4_body;
    public GUIStyle gui_icons_thing_r5_backpack;
    // === Mini-map ===
    public GUIStyle gui_gamescreen_symbol_mob;
    public GUIStyle gui_gamescreen_symbol_player;
    public GUIStyle gui_gamescreen_worldmap;
    public GUIStyle gui_gamescreen_greenhouse;
    public GUIStyle gui_gamescreen_temple;
    // Миниигра с открыванием замка
    public GUIStyle gui_minigame_doorlock_background;
    public GUIStyle gui_minigame_doorlock_kr1_1;
    public GUIStyle gui_minigame_doorlock_kr1_2;
    public GUIStyle gui_minigame_doorlock_kr1_3;
    public GUIStyle gui_minigame_doorlock_kr1_4;
    public GUIStyle gui_minigame_doorlock_kr2_1;
    public GUIStyle gui_minigame_doorlock_kr2_2;
    public GUIStyle gui_minigame_doorlock_kr2_3;
    public GUIStyle gui_minigame_doorlock_kr2_4;
    public GUIStyle gui_minigame_doorlock_kr3_1;
    public GUIStyle gui_minigame_doorlock_kr3_2;
    public GUIStyle gui_minigame_doorlock_kr3_3;
    public GUIStyle gui_minigame_doorlock_kr3_4;
    public GUIStyle gui_minigame_doorlock_krug1;
    public GUIStyle gui_minigame_doorlock_krug2;
    public GUIStyle gui_minigame_doorlock_krug3;
    public GUIStyle gui_minigame_doorlock_zasov_verh;
    public GUIStyle gui_minigame_doorlock_zasov1;
    public GUIStyle gui_minigame_doorlock_zasov2;
    public GUIStyle gui_minigame_doorlock_zasov3;
    // Музейная викторина
    public GUIStyle gui_hog2_icon_ammonit_160;
    public GUIStyle gui_hog2_icon_ammonit_436;
    public GUIStyle gui_hog2_icon_dinosaur_160;
    public GUIStyle gui_hog2_icon_dinosaur_436;
    public GUIStyle gui_hog2_icon_legionnaire_160;
    public GUIStyle gui_hog2_icon_legionnaire_436;
    public GUIStyle gui_hog2_icon_locomotive_160;
    public GUIStyle gui_hog2_icon_locomotive_436;
    public GUIStyle gui_hog2_icon_ship_160;
    public GUIStyle gui_hog2_icon_ship_436;
    public GUIStyle gui_hog2_icon_statue_egypt_160;
    public GUIStyle gui_hog2_icon_statue_egypt_436;
    // === HOG3 ===
    public GUIStyle gui_hog3_background;
    public GUIStyle gui_hog3_foreground;
    public GUIStyle gui_hog3_icon_extinguisher;
    public GUIStyle gui_hog3_icon_fishrod;
    public GUIStyle gui_hog3_icon_hammer;
    public GUIStyle gui_hog3_icon_recorder;
    public GUIStyle gui_hog3_icon_spray;
    public GUIStyle gui_hog3_icon_toaster;
    public GUIStyle gui_hog3_icon_tv;
    public GUIStyle gui_hog3_icon_watering;
    public GUIStyle gui_hog3_item_extinguisher;
    public GUIStyle gui_hog3_item_fishrod;
    public GUIStyle gui_hog3_item_hammer;
    public GUIStyle gui_hog3_item_recorder;
    public GUIStyle gui_hog3_item_spray;
    public GUIStyle gui_hog3_item_toaster;
    public GUIStyle gui_hog3_item_tv;
    public GUIStyle gui_hog3_item_watering;
    public GUIStyle gui_hog3_tv_sheet;
    // Викторина в кладовке
    public GUIStyle gui_hog3_icon_bicycle_160;
    public GUIStyle gui_hog3_icon_bicycle_436;
    public GUIStyle gui_hog3_icon_extinguisher_160;
    public GUIStyle gui_hog3_icon_extinguisher_436;
    public GUIStyle gui_hog3_icon_fishrod_160;
    public GUIStyle gui_hog3_icon_fishrod_436;
    public GUIStyle gui_hog3_icon_generator_160;
    public GUIStyle gui_hog3_icon_generator_436;
    public GUIStyle gui_hog3_icon_recorder_160;
    public GUIStyle gui_hog3_icon_recorder_436;
    public GUIStyle gui_hog3_icon_spray_160;
    public GUIStyle gui_hog3_icon_spray_436;
    public GUIStyle gui_hog3_icon_toaster_160;
    public GUIStyle gui_hog3_icon_toaster_436;
    public GUIStyle gui_hog3_icon_tv_160;
    public GUIStyle gui_hog3_icon_tv_436;
    public GUIStyle gui_hog3_icon_watering_160;
    public GUIStyle gui_hog3_icon_watering_436;
    // Игра про мозаику в подземелье
    public GUIStyle gui_minigame_mosaic_01;
    public GUIStyle gui_minigame_mosaic_02;
    public GUIStyle gui_minigame_mosaic_03;
    public GUIStyle gui_minigame_mosaic_04;
    public GUIStyle gui_minigame_mosaic_05;
    public GUIStyle gui_minigame_mosaic_06;
    public GUIStyle gui_minigame_mosaic_07;
    public GUIStyle gui_minigame_mosaic_08;
    public GUIStyle gui_minigame_mosaic_09;
    // Меню
    public GUIStyle gui_menuscreen_background;
    public GUIStyle gui_menuscreen_button;
    // === cursors ===========
    public GUIStyle cursor_default;
    public GUIStyle cursor_attack;
    public GUIStyle cursor_res;
    public GUIStyle cursor_take;
    // Global map
    public GUIStyle gui_worldmap_map;
    public GUIStyle gui_worldmap_player;
    public c_GuiCommonStyleController()
    {
        this.emptystyle = new GUIStyle();
        this.cf_blackscreenelement = new GUIStyle();
        this.gui_common_menu_background = new GUIStyle();
        this.gui_common_button_map = new GUIStyle();
        this.gui_common_button_map_hover = new GUIStyle();
        this.gui_common_button_ufo = new GUIStyle();
        this.gui_common_button_ufo_hover = new GUIStyle();
        this.gui_common_button_inventory = new GUIStyle();
        this.gui_common_button_inventory_hover = new GUIStyle();
        this.gui_common_button_exit = new GUIStyle();
        this.gui_common_button_exit_hover = new GUIStyle();
        this.gui_common_ufo_blur_background = new GUIStyle();
        this.gui_common_button_disabled = new GUIStyle();
        this.gui_common_button_normal = new GUIStyle();
        this.gui_common_button_red = new GUIStyle();
        this.gui_common_popup = new GUIStyle();
        this.gui_common_button_close = new GUIStyle();
        this.gui_common_button_close_dark = new GUIStyle();
        this.gui_common_minigame_window = new GUIStyle();
        this.gui_common_button_world = new GUIStyle();
        this.gui_loading_background = new GUIStyle();
        this.gui_loading_background_01 = new GUIStyle();
        this.gui_loading_background_02 = new GUIStyle();
        this.gui_loading_background_03 = new GUIStyle();
        this.gui_loading_background_04 = new GUIStyle();
        this.gui_loading_background_05 = new GUIStyle();
        this.gui_loading_logo = new GUIStyle();
        this.gui_loading_loader_back = new GUIStyle();
        this.gui_loading_loader = new GUIStyle();
        this.gui_worldmap_background = new GUIStyle();
        this.gui_worldmap_button_map = new GUIStyle();
        this.gui_worldmap_button_ship = new GUIStyle();
        this.gui_worldmap_button_character = new GUIStyle();
        this.gui_worldmap_button_shop = new GUIStyle();
        this.gui_worldmap_button_exit = new GUIStyle();
        this.gui_worldmap_button_entry = new GUIStyle();
        this.gui_test_background = new GUIStyle();
        this.gui_exitwindow_background = new GUIStyle();
        this.gui_test_button = new GUIStyle();
        this.gui_test_island = new GUIStyle();
        this.gui_test_sea = new GUIStyle();
        this.gui_inventory_background = new GUIStyle();
        this.gui_inventory_character = new GUIStyle();
        this.gui_inventory_drink = new GUIStyle();
        this.gui_inventory_food = new GUIStyle();
        this.gui_inventory_premium_icon = new GUIStyle();
        this.gui_inventory_hover_slot = new GUIStyle();
        this.gui_inventory_armor_icon = new GUIStyle();
        this.gui_inventory_backpack_icon = new GUIStyle();
        this.gui_inventory_boots_icon = new GUIStyle();
        this.gui_inventory_feature_icon = new GUIStyle();
        this.gui_inventory_gloves_icon = new GUIStyle();
        this.gui_inventory_weapons_icon = new GUIStyle();
        this.gui_inventory_button_make_out = new GUIStyle();
        this.gui_inventory_button_make_out_d = new GUIStyle();
        this.gui_inventory_button_use = new GUIStyle();
        this.gui_inventory_button_use_d = new GUIStyle();
        this.gui_inventory_button_trashbin = new GUIStyle();
        this.gui_inventory_button_trashbin_d = new GUIStyle();
        this.gui_inventory_experience = new GUIStyle();
        this.gui_inventory_experience_background = new GUIStyle();
        this.gui_inventory_experience_right_part = new GUIStyle();
        this.gui_inventory_athletics = new GUIStyle();
        this.gui_inventory_literature_languages = new GUIStyle();
        this.gui_inventory_maths = new GUIStyle();
        this.gui_inventory_natural_science = new GUIStyle();
        this.gui_inventory_cells = new GUIStyle();
        this.gui_inventory_cells_no_backpack = new GUIStyle();
        this.gui_inventory_symbol = new GUIStyle();
        this.gui_inventory_heart = new GUIStyle();
        this.gui_inventory_healthbar_full = new GUIStyle();
        this.gui_inventory_healthbar_empty = new GUIStyle();
        this.gui_inventory_armor = new GUIStyle();
        this.gui_inventory_damage = new GUIStyle();
        this.gui_inventory_status_fullhealth = new GUIStyle();
        this.thing_icons_shoes_test = new GUIStyle();
        this.gui_dialogue_background = new GUIStyle();
        this.gui_dialogue_hog2_background = new GUIStyle();
        this.gui_dialogue_hog3_background = new GUIStyle();
        this.gui_dialogue_block_add = new GUIStyle();
        this.gui_dialogue_block_background = new GUIStyle();
        this.gui_dialogue_button_close = new GUIStyle();
        this.gui_dialogue_button_left = new GUIStyle();
        this.gui_dialogue_button_right = new GUIStyle();
        this.gui_dialogue_button_yes = new GUIStyle();
        this.gui_dialogue_button_no = new GUIStyle();
        this.gui_dialogue_hero_avatar = new GUIStyle();
        this.gui_dialogue_masha_avatar = new GUIStyle();
        this.gui_dialogue_name_background = new GUIStyle();
        this.gui_dialogue_girl_avatar = new GUIStyle();
        this.gui_minigame_background = new GUIStyle();
        this.gui_minigame_slot = new GUIStyle();
        this.gui_minigame_mushroom_01 = new GUIStyle();
        this.gui_minigame_mushroom_02 = new GUIStyle();
        this.gui_minigame_mushroom_03 = new GUIStyle();
        this.gui_minigame_mushroom_04 = new GUIStyle();
        this.gui_minigame_mushroom_01_icon = new GUIStyle();
        this.gui_minigame_mushroom_02_icon = new GUIStyle();
        this.gui_minigame_mushroom_03_icon = new GUIStyle();
        this.gui_minigame_mushroom_04_icon = new GUIStyle();
        this.gui_minigame_mushroom_01_popup = new GUIStyle();
        this.gui_minigame_popup_background = new GUIStyle();
        this.gui_minigame_popup_ban = new GUIStyle();
        this.gui_minigame_popup_bigle_frowning = new GUIStyle();
        this.gui_minigame_popup_bigle_normal = new GUIStyle();
        this.gui_minigame_popup_smartie = new GUIStyle();
        this.gui_minigame_popup_wrong = new GUIStyle();
        this.gui_vegame_background = new GUIStyle();
        this.gui_vegame_slots = new GUIStyle();
        this.gui_vegame_button_long = new GUIStyle();
        this.gui_vegame_stone = new GUIStyle();
        this.gui_vegame_button_long_d = new GUIStyle();
        this.gui_vegame_stone_d = new GUIStyle();
        this.gui_vegame_hint = new GUIStyle();
        this.gui_vegame_popup = new GUIStyle();
        this.gui_vegame_sectoid = new GUIStyle();
        this.gui_vegame_sectoid_sad = new GUIStyle();
        this.gui_minigame_vegetable_01 = new GUIStyle();
        this.gui_minigame_vegetable_02 = new GUIStyle();
        this.gui_minigame_vegetable_03 = new GUIStyle();
        this.gui_minigame_vegetable_04 = new GUIStyle();
        this.gui_minigame_vegetable_05 = new GUIStyle();
        this.gui_minigame_vegetable_06 = new GUIStyle();
        this.gui_minigame_vegetable_07 = new GUIStyle();
        this.gui_minigame_vegetable_08 = new GUIStyle();
        this.gui_minigame_vegetable_09 = new GUIStyle();
        this.gui_minigame_vegetable_10 = new GUIStyle();
        this.gui_minigame_vegetable_11 = new GUIStyle();
        this.gui_minigame_vegetable_01_icon = new GUIStyle();
        this.gui_minigame_vegetable_02_icon = new GUIStyle();
        this.gui_minigame_vegetable_03_icon = new GUIStyle();
        this.gui_minigame_vegetable_04_icon = new GUIStyle();
        this.gui_minigame_vegetable_05_icon = new GUIStyle();
        this.gui_minigame_vegetable_06_icon = new GUIStyle();
        this.gui_minigame_vegetable_07_icon = new GUIStyle();
        this.gui_minigame_vegetable_08_icon = new GUIStyle();
        this.gui_minigame_vegetable_09_icon = new GUIStyle();
        this.gui_minigame_vegetable_10_icon = new GUIStyle();
        this.gui_minigame_vegetable_11_icon = new GUIStyle();
        this.gui_fishing_background = new GUIStyle();
        this.gui_fishing_frame = new GUIStyle();
        this.gui_fishing_counter = new GUIStyle();
        this.gui_fishing_worm = new GUIStyle();
        this.gui_fishing_hook = new GUIStyle();
        this.gui_fishing_rod_1 = new GUIStyle();
        this.gui_fishing_rod_1_select = new GUIStyle();
        this.gui_fishing_rod_2 = new GUIStyle();
        this.gui_fishing_rod_2_select = new GUIStyle();
        this.gui_fishing_rod_3 = new GUIStyle();
        this.gui_fishing_rod_3_select = new GUIStyle();
        this.gui_fish01_start = new GUIStyle();
        this.gui_fish01_idle = new GUIStyle();
        this.gui_fish01_end = new GUIStyle();
        this.gui_fish02_start = new GUIStyle();
        this.gui_fish02_idle = new GUIStyle();
        this.gui_fish02_end = new GUIStyle();
        this.gui_fish03_start = new GUIStyle();
        this.gui_fish03_idle = new GUIStyle();
        this.gui_fish03_end = new GUIStyle();
        this.gui_fishing_popup_success = new GUIStyle();
        this.gui_fishing_popup_failure = new GUIStyle();
        this.gui_fishing_popup_seatrout = new GUIStyle();
        this.gui_fishing_popup_seabass = new GUIStyle();
        this.gui_fishing_popup_mullet = new GUIStyle();
        this.gui_battlescreen_heart = new GUIStyle();
        this.gui_battlescreen_healtbar_background = new GUIStyle();
        this.gui_battlescreen_healtbar_health = new GUIStyle();
        this.gui_battlescreen_herolevel = new GUIStyle();
        this.gui_battlescreen_abilities_panel = new GUIStyle();
        this.gui_battlescreen_shad = new GUIStyle();
        this.gui_battlescreen_ability01 = new GUIStyle();
        this.gui_battlescreen_ability01_select = new GUIStyle();
        this.gui_battlescreen_ability02 = new GUIStyle();
        this.gui_battlescreen_ability03 = new GUIStyle();
        this.gui_battlescreen_ability04 = new GUIStyle();
        this.gui_battlescreen_ability05 = new GUIStyle();
        this.gui_battlescreen_ability06 = new GUIStyle();
        this.gui_battlescreen_livebattle = new GUIStyle();
        this.gui_battlescreen_mobhealth_background = new GUIStyle();
        this.gui_battlescreen_mobhealth = new GUIStyle();
        this.gui_craftscreen_panel_background = new GUIStyle();
        this.gui_craftscreen_icon = new GUIStyle();
        this.gui_craftscreen_selection = new GUIStyle();
        this.gui_craftscreen_tab_craft_active = new GUIStyle();
        this.gui_craftscreen_tab_craft_inactive = new GUIStyle();
        this.gui_craftscreen_tab_makeout_active = new GUIStyle();
        this.gui_craftscreen_tab_makeout_inactive = new GUIStyle();
        this.gui_library_background = new GUIStyle();
        this.gui_library_book_slots = new GUIStyle();
        this.gui_library_book_info = new GUIStyle();
        this.gui_library_book_unread = new GUIStyle();
        this.gui_library_book_read = new GUIStyle();
        this.gui_library_section = new GUIStyle();
        this.gui_library_booktitle_food = new GUIStyle();
        this.gui_library_booktitle_mushrooms = new GUIStyle();
        this.gui_library_booktitle_spacesuits = new GUIStyle();
        this.gui_library_booktitle_spiders = new GUIStyle();
        this.gui_library_booktitle_vegetables = new GUIStyle();
        this.gui_library_tab_health_n = new GUIStyle();
        this.gui_library_tab_health_s = new GUIStyle();
        this.gui_library_tab_biology_n = new GUIStyle();
        this.gui_library_tab_biology_s = new GUIStyle();
        this.gui_library_tab_geo_n = new GUIStyle();
        this.gui_library_tab_geo_s = new GUIStyle();
        this.gui_library_tab_tech_n = new GUIStyle();
        this.gui_library_tab_tech_s = new GUIStyle();
        this.gui_library_tab_history_n = new GUIStyle();
        this.gui_library_tab_history_s = new GUIStyle();
        this.gui_library_symbol = new GUIStyle();
        this.gui_library_icon_flash_food_on = new GUIStyle();
        this.gui_library_icon_flash_food_off = new GUIStyle();
        this.gui_library_icon_flash_mushrooms_on = new GUIStyle();
        this.gui_library_icon_flash_mushrooms_off = new GUIStyle();
        this.gui_library_icon_flash_skaf_on = new GUIStyle();
        this.gui_library_icon_flash_skaf_off = new GUIStyle();
        this.gui_library_icon_flash_spiders_on = new GUIStyle();
        this.gui_library_icon_flash_spiders_off = new GUIStyle();
        this.gui_library_icon_flash_vegetables_on = new GUIStyle();
        this.gui_library_icon_flash_vegetables_off = new GUIStyle();
        this.gui_ufoscreen_background = new GUIStyle();
        this.gui_ufoscreen_ufo = new GUIStyle();
        this.gui_ufoscreen_footnote1 = new GUIStyle();
        this.gui_ufoscreen_footnote2 = new GUIStyle();
        this.gui_ufoscreen_footnote3 = new GUIStyle();
        this.gui_ufoscreen_footnote4 = new GUIStyle();
        this.gui_ufoscreen_footnote5 = new GUIStyle();
        this.gui_ufoscreen_footnote6 = new GUIStyle();
        this.gui_ufoscreen_ufo_symbol = new GUIStyle();
        this.gui_kitchen_background = new GUIStyle();
        this.gui_kitchen_symbol = new GUIStyle();
        this.gui_kitchen_recipe_background = new GUIStyle();
        this.gui_kitchen_highlight_frame = new GUIStyle();
        this.gui_kitchen_ingridients_background = new GUIStyle();
        this.gui_workroom_symbol = new GUIStyle();
        this.gui_storage_background = new GUIStyle();
        this.gui_storage_background_no_backpack = new GUIStyle();
        this.gui_storage_symbol = new GUIStyle();
        this.gui_storage_faraway_background = new GUIStyle();
        this.gui_storage_faraway_background_no_backpack = new GUIStyle();
        this.gui_tutorial_ufo_dialogue_background = new GUIStyle();
        this.gui_tutorial_isle_dialogue_background = new GUIStyle();
        this.gui_tutorial_sectoid_avatar = new GUIStyle();
        this.gui_tutorial_cot_avatar = new GUIStyle();
        this.gui_tutorial_kitchen_select = new GUIStyle();
        this.gui_tutorial_fuckerarrow_up = new GUIStyle();
        this.gui_tutorial_fuckerarrow_down = new GUIStyle();
        this.gui_tutorial_fuckerarrow_left = new GUIStyle();
        this.gui_tutorial_fuckerarrow_right = new GUIStyle();
        this.gui_tutorial_icon_chicken_soup = new GUIStyle();
        this.gui_tutorial_icon_mushroom_soup = new GUIStyle();
        this.gui_tutorial_icon_potatoes_mushrooms = new GUIStyle();
        this.gui_tutorial_icon_fish_soup = new GUIStyle();
        this.gui_tutorial_icon_smoothies = new GUIStyle();
        this.gui_tutorial_icon_cabbage_soup = new GUIStyle();
        this.gui_tutorial_icon_food_chicken = new GUIStyle();
        this.gui_tutorial_icon_food_potatoes = new GUIStyle();
        this.gui_tutorial_icon_food_carrot = new GUIStyle();
        this.gui_tutorial_icon_food_onion = new GUIStyle();
        this.gui_tutorial_icon_feature = new GUIStyle();
        this.gui_tutorial_icon_paralizator = new GUIStyle();
        this.gui_tutorial_icon_blaster = new GUIStyle();
        this.gui_tutorial_flash_anim = new GUIStyle();
        this.gui_tutorial_fuckerarrow_sheet = new GUIStyle();
        this.gui_villa_background = new GUIStyle();
        this.gui_villa_symbol = new GUIStyle();
        this.gui_villa_button_hog = new GUIStyle();
        this.gui_hogscreen_panel = new GUIStyle();
        this.gui_hogscreen_button_help = new GUIStyle();
        this.gui_hogscreen_found = new GUIStyle();
        this.gui_hogscreen_help_fx = new GUIStyle();
        this.gui_hogscreen_goldenframe = new GUIStyle();
        this.gui_hogscreen_goldenframe_anim = new GUIStyle();
        this.gui_hog1_background = new GUIStyle();
        this.gui_hog1_item_swimming_mask = new GUIStyle();
        this.gui_hog1_item_blurf_board = new GUIStyle();
        this.gui_hog1_item_flippers = new GUIStyle();
        this.gui_hog1_item_mikroskop = new GUIStyle();
        this.gui_hog1_item_doll = new GUIStyle();
        this.gui_hog1_item_bear = new GUIStyle();
        this.gui_hog1_item_notebook = new GUIStyle();
        this.gui_hog1_item_book = new GUIStyle();
        this.gui_hog1_item_globus = new GUIStyle();
        this.gui_hog1_item_virt = new GUIStyle();
        this.gui_hog1_icon_swimming_mask = new GUIStyle();
        this.gui_hog1_icon_blurf_board = new GUIStyle();
        this.gui_hog1_icon_mikroskop = new GUIStyle();
        this.gui_hog1_icon_doll = new GUIStyle();
        this.gui_hog1_icon_bear = new GUIStyle();
        this.gui_hog1_icon_notebook = new GUIStyle();
        this.gui_hog1_icon_book = new GUIStyle();
        this.gui_hog1_icon_virt = new GUIStyle();
        this.gui_hog1_light = new GUIStyle();
        this.gui_hog1_virt_sheet = new GUIStyle();
        this.gui_hog2_background = new GUIStyle();
        this.gui_hog2_item_dinosaur = new GUIStyle();
        this.gui_hog2_item_ammonit = new GUIStyle();
        this.gui_hog2_item_locomotive = new GUIStyle();
        this.gui_hog2_item_statue_egypt = new GUIStyle();
        this.gui_hog2_item_ship = new GUIStyle();
        this.gui_hog2_item_legionnaire = new GUIStyle();
        this.gui_hog2_icon_dinosaur = new GUIStyle();
        this.gui_hog2_icon_ammonit = new GUIStyle();
        this.gui_hog2_icon_locomotive = new GUIStyle();
        this.gui_hog2_icon_statue_egypt = new GUIStyle();
        this.gui_hog2_icon_ship = new GUIStyle();
        this.gui_hog2_icon_legionnaire = new GUIStyle();
        this.gui_hog2_light = new GUIStyle();
        this.gui_hog2_ammonit_sheet = new GUIStyle();
        this.gui_museum_symbol = new GUIStyle();
        this.gui_museum_unknown = new GUIStyle();
        this.gui_museum_icon_virt = new GUIStyle();
        this.gui_museum_icon_ammonit = new GUIStyle();
        this.gui_exhibit_title_ammonit = new GUIStyle();
        this.gui_exhibit_title_cd = new GUIStyle();
        this.gui_noway_image = new GUIStyle();
        this.gui_RecipeItemIcon01 = new GUIStyle();
        this.gui_RecipeItemIcon02 = new GUIStyle();
        this.gui_RecipeItemIcon03 = new GUIStyle();
        this.gui_RecipeItemIcon04 = new GUIStyle();
        this.gui_RecipeItemIcon05 = new GUIStyle();
        this.gui_icons_loot_metal = new GUIStyle();
        this.gui_icons_loot_plastic = new GUIStyle();
        this.gui_icons_loot_cobweb = new GUIStyle();
        this.gui_icons_loot_deadspider = new GUIStyle();
        this.gui_icons_loot_eballon = new GUIStyle();
        this.gui_icons_loot_cactus = new GUIStyle();
        this.gui_icons_food_chicken_soup = new GUIStyle();
        this.gui_icons_food_cabbage_soup = new GUIStyle();
        this.gui_icons_food_mushroom_soup = new GUIStyle();
        this.gui_icons_food_mushroom_potatoes = new GUIStyle();
        this.gui_icons_food_fish_soup = new GUIStyle();
        this.gui_icons_food_pancake = new GUIStyle();
        this.gui_icons_food_smoothies = new GUIStyle();
        this.gui_icons_food_milkshape = new GUIStyle();
        this.gui_icons_food_banana = new GUIStyle();
        this.gui_icons_food_berries = new GUIStyle();
        this.gui_icons_food_cabbage = new GUIStyle();
        this.gui_icons_food_carrot = new GUIStyle();
        this.gui_icons_food_chicken = new GUIStyle();
        this.gui_icons_food_egg = new GUIStyle();
        this.gui_icons_food_fish = new GUIStyle();
        this.gui_icons_food_flour = new GUIStyle();
        this.gui_icons_food_milk = new GUIStyle();
        this.gui_icons_food_mushrooms = new GUIStyle();
        this.gui_icons_food_onion = new GUIStyle();
        this.gui_icons_food_orange = new GUIStyle();
        this.gui_icons_food_potatoes = new GUIStyle();
        this.gui_icons_food_sourcream = new GUIStyle();
        this.gui_icons_food_spice = new GUIStyle();
        this.gui_icons_food_beans = new GUIStyle();
        this.gui_icons_food_chickpea = new GUIStyle();
        this.gui_icons_food_corn = new GUIStyle();
        this.gui_icons_food_kidney_beans = new GUIStyle();
        this.gui_icons_food_lentils = new GUIStyle();
        this.gui_icons_food_peanut = new GUIStyle();
        this.gui_icons_food_peas = new GUIStyle();
        this.gui_icons_crystal_premium = new GUIStyle();
        this.gui_icons_thing_r3_backpack = new GUIStyle();
        this.gui_icons_thing_r3_gun = new GUIStyle();
        this.gui_icons_thing_r3_hand = new GUIStyle();
        this.gui_icons_thing_r4_gun = new GUIStyle();
        this.gui_icons_thing_r4_leg = new GUIStyle();
        this.gui_icons_thing_r4_hand = new GUIStyle();
        this.gui_icons_thing_r4_body = new GUIStyle();
        this.gui_icons_thing_r5_backpack = new GUIStyle();
        this.gui_gamescreen_symbol_mob = new GUIStyle();
        this.gui_gamescreen_symbol_player = new GUIStyle();
        this.gui_gamescreen_worldmap = new GUIStyle();
        this.gui_gamescreen_greenhouse = new GUIStyle();
        this.gui_gamescreen_temple = new GUIStyle();
        this.gui_minigame_doorlock_background = new GUIStyle();
        this.gui_minigame_doorlock_kr1_1 = new GUIStyle();
        this.gui_minigame_doorlock_kr1_2 = new GUIStyle();
        this.gui_minigame_doorlock_kr1_3 = new GUIStyle();
        this.gui_minigame_doorlock_kr1_4 = new GUIStyle();
        this.gui_minigame_doorlock_kr2_1 = new GUIStyle();
        this.gui_minigame_doorlock_kr2_2 = new GUIStyle();
        this.gui_minigame_doorlock_kr2_3 = new GUIStyle();
        this.gui_minigame_doorlock_kr2_4 = new GUIStyle();
        this.gui_minigame_doorlock_kr3_1 = new GUIStyle();
        this.gui_minigame_doorlock_kr3_2 = new GUIStyle();
        this.gui_minigame_doorlock_kr3_3 = new GUIStyle();
        this.gui_minigame_doorlock_kr3_4 = new GUIStyle();
        this.gui_minigame_doorlock_krug1 = new GUIStyle();
        this.gui_minigame_doorlock_krug2 = new GUIStyle();
        this.gui_minigame_doorlock_krug3 = new GUIStyle();
        this.gui_minigame_doorlock_zasov_verh = new GUIStyle();
        this.gui_minigame_doorlock_zasov1 = new GUIStyle();
        this.gui_minigame_doorlock_zasov2 = new GUIStyle();
        this.gui_minigame_doorlock_zasov3 = new GUIStyle();
        this.gui_hog2_icon_ammonit_160 = new GUIStyle();
        this.gui_hog2_icon_ammonit_436 = new GUIStyle();
        this.gui_hog2_icon_dinosaur_160 = new GUIStyle();
        this.gui_hog2_icon_dinosaur_436 = new GUIStyle();
        this.gui_hog2_icon_legionnaire_160 = new GUIStyle();
        this.gui_hog2_icon_legionnaire_436 = new GUIStyle();
        this.gui_hog2_icon_locomotive_160 = new GUIStyle();
        this.gui_hog2_icon_locomotive_436 = new GUIStyle();
        this.gui_hog2_icon_ship_160 = new GUIStyle();
        this.gui_hog2_icon_ship_436 = new GUIStyle();
        this.gui_hog2_icon_statue_egypt_160 = new GUIStyle();
        this.gui_hog2_icon_statue_egypt_436 = new GUIStyle();
        this.gui_hog3_background = new GUIStyle();
        this.gui_hog3_foreground = new GUIStyle();
        this.gui_hog3_icon_extinguisher = new GUIStyle();
        this.gui_hog3_icon_fishrod = new GUIStyle();
        this.gui_hog3_icon_hammer = new GUIStyle();
        this.gui_hog3_icon_recorder = new GUIStyle();
        this.gui_hog3_icon_spray = new GUIStyle();
        this.gui_hog3_icon_toaster = new GUIStyle();
        this.gui_hog3_icon_tv = new GUIStyle();
        this.gui_hog3_icon_watering = new GUIStyle();
        this.gui_hog3_item_extinguisher = new GUIStyle();
        this.gui_hog3_item_fishrod = new GUIStyle();
        this.gui_hog3_item_hammer = new GUIStyle();
        this.gui_hog3_item_recorder = new GUIStyle();
        this.gui_hog3_item_spray = new GUIStyle();
        this.gui_hog3_item_toaster = new GUIStyle();
        this.gui_hog3_item_tv = new GUIStyle();
        this.gui_hog3_item_watering = new GUIStyle();
        this.gui_hog3_tv_sheet = new GUIStyle();
        this.gui_hog3_icon_bicycle_160 = new GUIStyle();
        this.gui_hog3_icon_bicycle_436 = new GUIStyle();
        this.gui_hog3_icon_extinguisher_160 = new GUIStyle();
        this.gui_hog3_icon_extinguisher_436 = new GUIStyle();
        this.gui_hog3_icon_fishrod_160 = new GUIStyle();
        this.gui_hog3_icon_fishrod_436 = new GUIStyle();
        this.gui_hog3_icon_generator_160 = new GUIStyle();
        this.gui_hog3_icon_generator_436 = new GUIStyle();
        this.gui_hog3_icon_recorder_160 = new GUIStyle();
        this.gui_hog3_icon_recorder_436 = new GUIStyle();
        this.gui_hog3_icon_spray_160 = new GUIStyle();
        this.gui_hog3_icon_spray_436 = new GUIStyle();
        this.gui_hog3_icon_toaster_160 = new GUIStyle();
        this.gui_hog3_icon_toaster_436 = new GUIStyle();
        this.gui_hog3_icon_tv_160 = new GUIStyle();
        this.gui_hog3_icon_tv_436 = new GUIStyle();
        this.gui_hog3_icon_watering_160 = new GUIStyle();
        this.gui_hog3_icon_watering_436 = new GUIStyle();
        this.gui_minigame_mosaic_01 = new GUIStyle();
        this.gui_minigame_mosaic_02 = new GUIStyle();
        this.gui_minigame_mosaic_03 = new GUIStyle();
        this.gui_minigame_mosaic_04 = new GUIStyle();
        this.gui_minigame_mosaic_05 = new GUIStyle();
        this.gui_minigame_mosaic_06 = new GUIStyle();
        this.gui_minigame_mosaic_07 = new GUIStyle();
        this.gui_minigame_mosaic_08 = new GUIStyle();
        this.gui_minigame_mosaic_09 = new GUIStyle();
        this.gui_menuscreen_background = new GUIStyle();
        this.gui_menuscreen_button = new GUIStyle();
        this.cursor_default = new GUIStyle();
        this.cursor_attack = new GUIStyle();
        this.cursor_res = new GUIStyle();
        this.cursor_take = new GUIStyle();
        this.gui_worldmap_map = new GUIStyle();
        this.gui_worldmap_player = new GUIStyle();
    }

}