using System.Collections;

/*****************************************************************************************
* Strings variables
* 
* @author N-Game Studios 
* Research & Development	
* 
*****************************************************************************************/
[System.Serializable]
public class Strings : object
{
    public static string string001;
    public static string string002;
    public static string string003;
    public static string string004;
    public static string string005;
    public static string string006;
    public static string string007;
    public static string string008;
    public static string string009;
    public static string string010;
    public static string string011;
    public static string string012;
    public static string string013;
    public static string string014;
    public static string string015;
    public static string string016;
    public static string string017;
    public static string string018;
    public static string string019;
    public static string string020;
    public static string string021;
    public static string string022;
    public static string string023;
    public static string string024;
    public static string string025;
    public static string string026;
    public static string string027;
    public static string string028;
    public static string string029;
    public static string string030;
    public static string string031;
    public static string string032;
    public static string string033;
    public static string string034;
    public static string string035;
    public static string string036;
    public static string string037;
    public static string string038;
    public static string string039;
    public static string string040;
    public static string string041;
    public static string string042;
    //TUTORIAL на корабле
    public static string string043;
    public static string string044;
    public static string string045;
    public static string string046;
    public static string string047;
    public static string string048;
    public static string string049;
    public static string string050;
    public static string string051;
    public static string string052;
    public static string string053;
    public static string string053_1;
    public static string string053_2;
    public static string string054;
    public static string string055;
    public static string string056;
    public static string string057;
    public static string string058;
    public static string string059;
    public static string string060;
    public static string string061;
    public static string string062;
    public static string string063;
    public static string string064;
    public static string string065;
    public static string string066;
    public static string string067;
    public static string string068;
    public static string string069;
    public static string string070;
    public static string string071;
    public static string string072;
    public static string string073;
    public static string string074;
    public static string string075;
    public static string string076;
    public static string string077;
    public static string string078;
    public static string string079;
    public static string string080;
    public static string string081;
    public static string string082;
    public static string string083;
    public static string string084;
    public static string string085;
    public static string string086;
    public static string string087;
    public static string string088;
    public static string string089;
    public static string string090;
    public static string string091;
    public static string string092;
    public static string string093;
    public static string string094;
    public static string string095;
    public static string string096;
    public static string string097;
    public static string string098;
    public static string string099;
    public static string string100;
    public static string string101;
    public static string string102;
    public static string string103;
    public static string string104;
    public static string string105;
    public static string string106;
    public static string string107;
    public static string string108;
    public static string string109;
    public static string string110;
    public static string string111;
    public static string string112;
    public static string string113;
    public static string string114;
    public static string string115;
    public static string string116;
    public static string string117;
    public static string string118;
    public static string string119;
    public static string string120;
    public static string string121;
    public static string string122;
    public static string string123;
    public static string string124;
    public static string string125;
    public static string string126;
    public static string string127;
    public static string string128;
    public static string string129;
    public static string string130;
    public static string string131;
    public static string string132;
    public static string string133;
    public static string string134;
    public static string string135;
    public static string string136;
    public static string string137;
    public static string string138;
    public static string string139;
    public static string string140;
    public static string string141;
    public static string string142;
    public static string string143;
    public static string string144;
    public static string string145;
    public static string string146;
    public static string string147;
    public static string string148;
    public static string string149;
    public static string string150;
    public static string string151;
    public static string string152;
    public static string string153;
    public static string string154;
    public static string string155;
    public static string string156;
    public static string string157;
    public static string string158;
    public static string string159;
    public static string string160;
    public static string string161;
    public static string string162;
    public static string string163;
    public static string string164;
    public static string string165;
    public static string string166;
    public static string string167;
    public static string string168;
    public static string string169;
    public static string string170;
    public static string string171;
    public static string string172;
    public static string string173;
    public static string string174;
    public static string string175;
    public static string string176;
    public static string string177;
    public static string string178;
    public static string string179;
    public static string string180;
    public static string string181;
    public static string string182;
    public static string string183;
    public static string string184;
    public static string string185;
    public static string string186;
    public static string string187;
    public static string string188;
    public static string string189;
    public static string string190;
    public static string string191;
    public static string string192;
    public static string string193;
    public static string string194;
    public static string string195;
    public static string string196;
    public static string string197;
    public static string string198;
    public static string string199;
    public static string string200;
    public static string string201;
    public static string string202;
    public static string string203;
    public static string string204;
    public static string string205;
    public static string string206;
    public static string string207;
    public static string string208;
    public static string string209;
    public static string string210;
    public static string string211;
    public static string string212;
    public static string string213;
    public static string string214;
    public static string string215;
    public static string string216;
    public static string string217;
    public static string string218;
    public static Hashtable nemo_dlg01;
    public static Hashtable nemo_dlg02;
    static Strings()
    {
        Strings.string001 = "Loading...";
        Strings.string002 = "Initialization...";
        Strings.string003 = "SHIP SCREEN";
        Strings.string004 = "CHARACTER SCREEN";
        Strings.string005 = "STORE SCREEN";
        Strings.string006 = "Хотите выйти из игры?";
        Strings.string007 = "Да";
        Strings.string008 = "Нет";
        Strings.string009 = "Isla de Muerta";
        Strings.string010 = "Do you want to land on the island?";
        Strings.string011 = "High seas";
        Strings.string012 = "Do you want to go to the sea?";
        Strings.string013 = "Использовать";
        Strings.string014 = "Разобрать";
        Strings.string015 = "Снять";
        Strings.string016 = "Какой гриб съедобен?";
        Strings.string017 = "Ты нашёл: Белый гриб";
        Strings.string018 = "OK";
        Strings.string019 = "Это же ";
        Strings.string020 = "Мухомор";
        Strings.string021 = "Сморчок";
        Strings.string022 = "Поганка";
        Strings.string023 = "Ещё раз";
        Strings.string024 = "Вы поймали морскую форель!";
        Strings.string025 = "Вы поймали морского окуня!";
        Strings.string026 = "Вы поймали кефаль!";
        Strings.string027 = "Рыба сорвалась, попробуйте ещё раз.";
        Strings.string028 = "КРАФТ";
        Strings.string029 = "МАСТЕРСКАЯ";
        Strings.string030 = "Для создания необходимо:";
        Strings.string031 = "СОЗДАТЬ";
        Strings.string032 = "Вы создали предмет";
        Strings.string033 = "БИБЛИОТЕКА";
        Strings.string034 = "Здоровье";
        Strings.string035 = "Биология";
        Strings.string036 = "Техника";
        Strings.string037 = "Изучить";
        Strings.string038 = "Вы подняли предмет: ";
        Strings.string039 = "Вы получите:";
        Strings.string040 = "Разобрать";
        Strings.string041 = "Тело";
        Strings.string042 = "Разум";
        Strings.string043 = "Куратор";
        Strings.string044 = "Макс, ведь ты впервые на чужой планете. Давай-ка, я напомню тебе о твоих возможностях.";
        Strings.string045 = "Вот какими отсеками корабля ты можешь пользоваться.";
        Strings.string046 = "Рубка";
        Strings.string047 = "Рубка управления в центре, но тебе она пока не понадобится.";
        Strings.string048 = "Склад";
        Strings.string049 = "Здесь Склад – сюда ты будешь собирать все интересное и полезное, что найдешь снаружи корабля.";
        Strings.string050 = "Мастерская";
        Strings.string051 = "Вот Мастерская и Лаборатория – тут можешь проводить опыты, поработать с найденными предметами и создать что-то новое.";
        Strings.string052 = "Библиотека";
        Strings.string053 = "Это Библиотека – главная часть твоего школьного проекта. Можно сказать, хранилище разведанных знаний. Когда заполнишь Библиотеку до конца – считай, что твоё задание выполнено на «отлично».";
        Strings.string053_1 = "Музей";
        Strings.string053_2 = "Здесь Музей, в котором будут храниться самые ценные артефакты человеческой цивилизации, которые ты сможешь отыскать.";
        Strings.string054 = "Кухня";
        Strings.string055 = "А здесь находится Кухня. Чтобы поддерживать здоровье и хорошее настроение, ты сам будешь готовить пищу из местных продуктов. Кстати, пора что-нибудь приготовить! Пошли-ка на Кухню, Макс.";
        Strings.string056 = "Корабль";
        Strings.string057 = "Куриный суп";
        Strings.string058 = "Грибной суп";
        Strings.string059 = "Картошка с грибами";
        Strings.string060 = "Уха";
        Strings.string061 = "К счастью, у нас имеется немного продуктов. Посмотри на список рецептов и на компоненты, необходимые для приготовления каждого блюда. Выбери тот рецепт, для которого у нас достаточно продуктов.";
        Strings.string062 = "Необходимо:";
        Strings.string063 = "Создать";
        Strings.string064 = "Кухня";
        Strings.string065 = "Добавляет:";
        Strings.string066 = "Здоровье +15";
        Strings.string067 = "Добавляет +15 к Здоровью кота.";
        Strings.string068 = "Отличный суп получился! Теперь он находится в термосе твоего скафандра. Когда почувствуешь голод – куриный супчик будет очень кстати.";
        Strings.string069 = "Знания о Земле собираются здесь, в Библиотеке. Изучай всё внимательно – Библиотека поможет разобраться с любыми проблемами.";
        Strings.string070 = "Вот как раз активировался книгомульт о пищевой ценности продуктов. Посмотри его до конца – и получишь награду.";
        Strings.string071 = "Библиотека";
        Strings.string072 = "Пищевая ценность продуктов";
        Strings.string073 = "То, что качество и состав пищи влияют на самочувствие, работоспособность и выносливость, люди поняли очень давно. Примерно в 400 году до н.э. Геродот призывал: «Позвольте пище быть вашим лекарством, а лекарствам – вашей пищей». Главный источник энергии - это макронутриенты: жиры, белки, углеводы. Помимо них необходим целый набор микронутриентов - витаминов, минеральных веществ, микроэлементов, биологически активных компонентов. Это больше сотни химических соединений.";
        Strings.string074 = "Смотреть";
        Strings.string075 = "Новый рецепт!";
        Strings.string076 = "Фруктовый смузи";
        Strings.string077 = "Видишь, Макс, ты посмотрел книгомульт – и открыл новый кулинарный рецепт – Фруктовый смузи. Поздравляю! Когда соберешь на планете апельсины, бананы и ягоды, можешь попробовать его приготовить.";
        Strings.string078 = "Макс";
        Strings.string079 = "Я вижу, что книгомульты не только интересные, но и полезные! Посмотрев их, я буду получать новые рецепты для создания предметов?";
        Strings.string080 = "Да, каждый книгомульт откроет новую схему или рецепт.";
        Strings.string081 = "Тогда я хочу посмотреть их побольше! Чтобы открыть все и поскорее!";
        Strings.string082 = "Впереди тебя ждут не только тайны и приключения, Макс, но также задачки для ума. Решай их правильно – и получай книгомульты в награду!";
        Strings.string083 = "Наверное, я тебя уже немного утомил, продолжим обучение позже. А теперь ты готов для первой вылазки?";
        Strings.string084 = "Отлично! Тогда нажми кнопку «Карта» на нижней панели.";
        Strings.string085 = "Хорошо, можешь пока побродить по кораблю, а когда будешь готов, то нажми кнопку «Карта» на нижней панели.";
        Strings.string086 = "География";
        Strings.string087 = "История";
        Strings.string088 = "Этот книгомульт пока не доступен для изучения.";
        Strings.string089 = "Внимание!";
        Strings.string090 = "Недостаточно ингридиентов для приготовления блюда!";
        Strings.string091 = "Вы приготовили блюдо";
        Strings.string092 = "Недостаточно компонентов для создания предмета!";
        Strings.string093 = "Инвентарь";
        Strings.string094 = "Надеть";
        Strings.string095 = "Снять";
        Strings.string096 = "Съесть";
        Strings.string097 = "Взять";
        Strings.string098 = "Склад";
        Strings.string099 = "Учитель, как мне лучше пополнить запасы продуктов? Охотой или рыбалкой? А может поискать дикорастущие фрукты и овощи?";
        Strings.string100 = "Ты правильно рассуждаешь, Макс. Но тебе ещё придется научиться всем этим способам. А пока рекомендую проверить старую оранжерею.";
        Strings.string101 = "Хоть оранжерея давно заброшена, это лучшее место для поиска овощей и фруктов, чем дикие джунгли.";
        Strings.string102 = "Но, Учитель, я почти не знаком со съедобными растениями этой планеты. Как отличить их от ядовитых?";
        Strings.string103 = "Хорошо, я активирую в Библиотеке книгомульт «Овощи». Но вначале давай проверим твои знания. Пройди тест – и получи за каждый правильный ответ 1 кристалл.";
        Strings.string104 = "Где Картофель?";
        Strings.string105 = "Картофель";
        Strings.string106 = "Перец";
        Strings.string107 = "Редис";
        Strings.string108 = "Умничка!";
        Strings.string109 = "Правильный выбор!";
        Strings.string110 = "Не верно";
        Strings.string111 = "Попробуй ещё раз";
        Strings.string112 = "Помочь за 1";
        Strings.string113 = "Где Баклажан?";
        Strings.string114 = "Где Свекла?";
        Strings.string115 = "Где Сельдерей?";
        Strings.string116 = "Где Лук?";
        Strings.string117 = "Где Капуста?";
        Strings.string118 = "Новый книгомульт!";
        Strings.string119 = "В Библиотеке активирован новый книгомульт «Овощи».";
        Strings.string120 = "Смотреть";
        Strings.string121 = "Позже";
        Strings.string122 = "Щи";
        Strings.string123 = "Внимание, опасность! Гигантские пауки-мутанты! В Библиотеке активирован книгомульт «Пауки». Посмотри его немедленно!";
        Strings.string124 = "Активатор";
        Strings.string125 = "Мастерская";
        Strings.string126 = "К сожалению, для создания этого улучшения не хватает компонентов. Вначале надо победить паука.";
        Strings.string127 = "Как же мне это сделать? Ведь нужно какое-то оружие?";
        Strings.string128 = "Твой скафандр – сам по себе оружие. Я сейчас активирую ещё один книгомульт – «Скафандры». Посмотри его – и получи другую схему для улучшения.";
        Strings.string129 = "Резак";
        Strings.string130 = "Добавляет +15 к Урону кота.";
        Strings.string131 = "Чтобы установить улучшение на скафандр, ты должен вернуться на корабль. Заодно выгрузишь собранные овощи на Склад.";
        Strings.string132 = "Вилла";
        Strings.string133 = "Ты нашёл: ";
        Strings.string134 = "Вирт";
        Strings.string135 = "Аммонит";
        Strings.string136 = "Найдите экспонат для этой ячейки музея.";
        Strings.string137 = "Музей";
        Strings.string138 = "Непроходимый завал";
        Strings.string139 = "Музей";
        Strings.string140 = "Ингридиент";
        Strings.string141 = "Вы далеко, для выгрузки вещей вернитесь на корабль.";
        Strings.string142 = "Инвентарь заполнен!";
        Strings.string143 = "И вот ты уже не безоружен. Можешь пойти и разделаться с той паутиной.";
        Strings.string144 = "Паук тебя атакует! Скафандр хорошо защищает от смертельных ран, но кое-какие повреждения могут пройти даже сквозь него. Будь осторожен и атакуй в ответ!";
        Strings.string145 = "За долгие годы паук создал в оранжерее такую удивительную атмосферу, что она благоприятно влияет на рост грибов.";
        Strings.string146 = "Они съедобные? Я могу собрать грибы и приготовить грибной суп или другие блюда!";
        Strings.string147 = "Тебе самому предстоит разобраться, какой гриб съедобный, а какой ядовитый. Будь внимателен – от правильного выбора зависит твоя награда.";
        Strings.string148 = "В общих чертах ты уже понимаешь, как выживать в этом мире. Ты умеешь сражаться, собирать компоненты и делать из них пищу и другие полезные вещи.";
        Strings.string149 = "Спасибо, Учитель! Я действительно очень умный, красивый и талантливый!";
        Strings.string150 = "Хвастаться нехорошо, лучше доказывай свои таланты добрыми делами. Исследуй мир, пополняй библиотеку книгомультов, собирай знания.";
        Strings.string151 = "И куда мне отправиться в первую очередь?";
        Strings.string152 = "Выбирай сам, что тебе больше нравится. Можешь исследовать заброшенную виллу или отправиться на рыбалку. А когда изучишь всё вокруг, то отправляйся на экскурсию в джунгли или заброшенную деревню. Там много интересного. И опасного, конечно же.";
        Strings.string153 = "В Библиотеке активирован новый книгомульт «Грибы».";
        Strings.string154 = "Будь осторожен, Макс! Это старое полуразрушенное здание, здесь может быть небезопасно.";
        Strings.string155 = "Однако это самый привлекательный дом для исследования! Я просто обязан обыскать его, Учитель.";
        Strings.string156 = "Ну что ж, попробуй. Сканеры показывают, что несколько комнат уцелело и сохранилось почти в первозданном виде. Постарайся найти там интересные для изучения предметы.";
        Strings.string157 = "В прошлый раз ты обследовал не все закутки этого дома. Посмотри получше, может здесь ещё осталось что-то интересное.";
        Strings.string158 = "Сканеры сообщают, что здесь не осталось больше ничего интересного.";
        Strings.string159 = "Привет! Я так рада, что… Ой! Котик?!";
        Strings.string160 = "Муррр, конечно, но вряд ли я такой котик, как ты подумала…";
        Strings.string161 = "Да-да, ты говорящий и невероятный обаятельный! Ты робот, да?";
        Strings.string162 = "За обаятельного спасибо, а вот на робота я бы мог и обидеться, если бы умел обижаться. Скажу тебе правду: я вообще не с вашей планеты.";
        Strings.string163 = "Очень жаль… А я уж понадеялась, что земные котики поумнели и создали новую цивилизацию, которая не повторит ошибок людей.";
        Strings.string164 = "Ты много об этом знаешь? Можешь рассказать мне о закате вашей цивилизации?";
        Strings.string165 = "Могу, конечно, только давай вначале познакомимся. Меня зовут Зоя. Я не имею настоящего тела и живу в этом приборе, словно призрак. А как тебя зовут?";
        Strings.string166 = "Я Макс. Так ты искусственный интеллект?";
        Strings.string167 = "Теперь настал мой черед обижаться. Я не ИИ, а полное и абсолютное отражение настоящей девочки, всю жизнь прожившей в этом доме.";
        Strings.string168 = "Она умерла?";
        Strings.string169 = "Давай я расскажу тебе обо всём по порядку, хорошо?";
        Strings.string170 = "Послушать рассказ Зои?";
        Strings.string171 = "Ладно, включи прибор позже – мы поговорим, когда у тебя найдётся время.";
        Strings.string172 = "Готов узнать историю падения нашей цивилизации? ";
        Strings.string173 = "Потому мне пришлось отключиться от общей Сети и остаться в собственном закрытом мирке. Он, конечно, хорош, но я теперь как птица в золотой клетке. Такая жизнь не приносит счастья, если рядом нет настоящих друзей.";
        Strings.string174 = "Так что я очень рада с тобой познакомиться, Макс!";
        Strings.string175 = "Включить";
        Strings.string176 = "Привет, Макс. Извини, я сейчас занята – появились срочные дела в виртуальности. Я дам тебе знать, как освобожусь.";
        Strings.string177 = "Макс, ты обнаружил очень интересные предметы. Но чтобы хоть немного понимать их ценность, пройди, пожалуйста, археологическую викторину.";
        Strings.string178 = "Кто появился в девонском периоде?";
        Strings.string179 = "Что относится к истории Римской Империи?";
        Strings.string180 = "Что было создано в 1801 году?";
        Strings.string181 = "Телевизор";
        Strings.string182 = "Макс, здесь так много предметов человеческого быта. Пройди викторину, чтобы узнать о них получше.";
        Strings.string183 = "Где устройство для приготовления еды?";
        Strings.string184 = "Где садовый инвентарь?";
        Strings.string185 = "С помощью чего можно слушать музыку?";
        Strings.string186 = "Рыба – идеальная пища для тебя, Макс. Поймаешь её – приготовишь отличную уху! Рецепт у тебя уже записан.";
        Strings.string187 = "Как это делать, Учитель? На нашей планете не бывает дикой рыбы…";
        Strings.string188 = "Следи за тем, какая рыба показалась из воды – и быстро выбирай подходящую снасть. Правильный выбор удочки – залог успеха.";
        Strings.string189 = "Не жадничай, Макс! У тебя уже есть достаточный запас рыбы. Если ловить дальше, то рыба просто испортится.";
        Strings.string190 = "Вы правы, Учитель. Незачем бессмысленно убивать живых существ, я ведь не голодаю.";
        Strings.string191 = "Хитрый замок охраняет вход в этот храм. Будешь разбираться сам или хочешь потратить 5 кристаллов, чтобы получить подсказку?";
        Strings.string192 = "Хочешь потратить 5 кристаллов и получить подсказку?";
        Strings.string193 = "Двери откроются, если сработают все три замка. На каждом из них изображены символы, один из которых лишний. Нажми на него. Если ты угадал правильно - засов сдвинется.";
        Strings.string194 = "Эта дверь заперта на ключ. К счастью, сканеры подсказывают, что он спрятан в одной из дальних комнат. Отыщи ключ и вернись сюда, Макс.";
        Strings.string195 = "Это гробница какого-то очень древнего царя. Однако, чтобы узнать подробности, требуется восстановить разбитый барельеф.";
        Strings.string196 = "Да, я вижу кучу осколков. Предлагаете мне заняться составлением из них пазла?";
        Strings.string197 = "Можно и так сказать. Но я бы назвал этот процесс: «реконструкция». Если дотронешься до любой ячейки, она поменяется местами с соседней по горизонтали. Собери правильное изображение.";
        Strings.string198 = "Отличная работа, Макс! Ты восстановил барельеф со сценой из жизни ольмекского царя. В качестве приза я активировал в Библиотеке книгомульт «Индейцы».";
        Strings.string199 = "Сдаваться – это плохо, Макс. Когда отдохнешь, вернись к этой задаче и попробуй снова.";
        Strings.string200 = "В Библиотеке активирован новый книгомульт «Индейцы».";
        Strings.string201 = "Получен новый уровень: ";
        Strings.string202 = "Перенести";
        Strings.string203 = "Парализатор";
        Strings.string204 = "Где белый гриб?";
        Strings.string205 = "Где сморчок?";
        Strings.string206 = "Где мухомор?";
        Strings.string207 = "Меню";
        Strings.string208 = "Продолжить";
        Strings.string209 = "Сохранить";
        Strings.string210 = "Загрузить";
        Strings.string211 = "Выйти из игры";
        Strings.string212 = "Игра сохранена";
        Strings.string213 = "Хочешь загрузить последнее сохранение?";
        Strings.string214 = "Хочешь выйти из игры?\nИгра будет сохранена.";
        Strings.string215 = "Забрать";
        Strings.string216 = "Внезапный финал";
        Strings.string217 = "К сожалению, условия жизни на этой планете оказались для Вас слишком суровыми. В следующий раз будьте осторожней!";
        Strings.string218 = "Выход";
        Strings.nemo_dlg01 = new Hashtable(new Hashtable() { {"0", new Hashtable() { {"speaker", "npc_girl" },  {"name", "Маша Мухоморова" },  {"image", "gui_dialogue_masha_avatar" },  {"text", "Привет! Смотри, сколько здесь грибов! Хочешь съесть один грибочек?" },  {"type", "normal" }, } },  {"1", new Hashtable() { {"speaker", "hero" },  {"name", "hero:" },  {"image", "gui_dialogue_hero_avatar" },  {"text", "Ну, я даже не знаю... Не хотелось бы наесться поганок." },  {"type", "normal" }, } },  {"2", new Hashtable() { {"speaker", "npc_girl" },  {"name", "Маша Мухоморова" },  {"image", "gui_dialogue_masha_avatar" },  {"text", "Не бойся! Если ошибёшься, я подскажу тебе. Ну что, попробуем?" },  {"type", "choice" }, } }, });
        Strings.nemo_dlg02 = new Hashtable(new Hashtable() { {"0", new Hashtable() { {"speaker", "hero" },  {"name", "hero:" },  {"image", "gui_dialogue_hero_avatar" },  {"text", "Доброго здоровья, дед Щукарь! Много рыбы уже наловили, хорошо клюёт?" },  {"type", "normal" }, } },  {"1", new Hashtable() { {"speaker", "npc_ded" },  {"name", "Дед Щукарь" },  {"image", "gui_dialogue_ded_avatar" },  {"text", "И тебе не хворать! Клёв хороший, а рыбы в море на всех хватит. Если хочешь, присоединяйся!" },  {"type", "choice" }, } }, });
    }

}